name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Secrets
        run: |
          echo "VM_USERNAME: ${{ secrets.VM_USERNAME }}"
          echo "VM_IP: ${{ secrets.VM_IP }}"
        shell: bash

      - name: SSH into VM and Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            echo "Deploying to VM..."
            cd /home/your_username/your_app
            git config --global user.name "Your Name"
            git config --global user.email "your_email@example.com"
            git pull origin main
            docker-compose up -d
            echo "Deployment complete."