# Nome do Workflow
name: Deploy to VM

# Gatilho: Executa sempre que houver um push na branch 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # O tipo de máquina que o job vai rodar
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o checkout do seu código do repositório para a máquina da Action
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Conecta na sua VM via SSH e executa o script de deploy
      - name: SSH into VM and Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          # IP da sua VM, vindo dos segredos do GitHub
          host: ${{ secrets.VM_IP }}
          # Usuário na VM para fazer login
          username: ${{ secrets.VM_USERNAME }} # Deve ser 'felipe'
          # Sua chave SSH privada, vinda dos segredos do GitHub
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Porta SSH, o padrão é 22
          port: 22
          # Script que será executado na VM
          script: |
            set -e
            echo "Deploying to VM..."
            # Cria o diretório da aplicação se não existir
            mkdir -p /home/***/advini-inss  # Substitua *** pelo seu nome de usuário
            cd /home/***/advini-inss # Substitua *** pelo seu nome de usuário
            git config --global user.name "Seu Nome"
            git config --global user.email "seu_email@exemplo.com"
            git pull origin main
            docker compose up -d
            echo "Deployment complete."

